In [1]:
import numpy as np

### Declare a scalar

In [4]:
s= 5

In [6]:
s

5

### Declare a Vector

In [13]:
v = np.array([5,-2,4])

In [15]:
v

array([ 5, -2,  4])

### Declare a Matrix

In [18]:
m = np.array([[5,12,6],[-3,0,14]])

In [20]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data Types

In [23]:
type(s)

int

In [25]:
type(v)

numpy.ndarray

In [27]:
type(m)

numpy.ndarray

In [29]:
s_array = np.array(5)
s_array

array(5)

In [31]:
type(s_array)

numpy.ndarray

### Data Shapes Using .shape

In [39]:
m.shape

(2, 3)

In [41]:
v.shape

(3,)

In [43]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [45]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [47]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [49]:
s_array.shape

()

### Create a Tensor

In [52]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [54]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [56]:
 t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [58]:
t.shape

(2, 2, 3)

In [60]:
t_manual = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [62]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [64]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [66]:
m1+1

array([[ 6, 13,  7],
       [-2,  1, 15]])

### Tanspose of a Matrix

In [69]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [73]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])
np.dot(x,y)

-66

In [75]:
np.dot(2,x)

array([ 4, 16, -8])

In [77]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [79]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [81]:
3*m1

array([[15, 36, 18],
       [-9,  0, 42]])

In [85]:
m3 = np.array([2,3,4])

In [87]:
np.dot(m1,m3)

array([70, 50])